- craft_archives/errors.py
- craft_archives/os_release.py
- craft_archives/repo/__init__.py
- craft_archives/repo/apt_key_manager.py
- craft_archives/repo/apt_ppa.py
- craft_archives/repo/apt_sources_manager.py
- craft_archives/repo/errors.py
- craft_archives/repo/installer.py
- craft_archives/repo/package_repository.py
- craft_archives/repo/projects.py
- craft_archives/utils.py
- pyproject.toml
- tests/unit/repo/test_apt_key_manager.py
- tests/unit/repo/test_apt_ppa.py
- tests/unit/repo/test_apt_sources_manager.py
- tests/unit/repo/test_installer.py
- tests/unit/repo/test_package_repository.py
- tests/unit/repo/test_projects.py
- tox.ini
This is the same PR as before; I had to re-create it because when this repo was made public the "link" to my fork was broken, so I couldn't update the code anymore. I squashed a commit and reworded some messages, but that's all.
---
CRAFT-1549
> move repo code

- .github/renovate.json5
- craft_archives/repo/apt_key_manager.py
- craft_archives/repo/apt_ppa.py
- pyproject.toml
- tests/integration/test_nothing.py
- tox.ini
Pull in updated configuration from starbase.
Includes sphinx configuration for tox, but does not include actual documentation files.
> base: Align to latest starbase standards

- docs/conf.py
- docs/explanation/index.rst
- docs/howto/index.rst
- docs/index.rst
- docs/reference/index.rst
- docs/tutorials/index.rst
- pyproject.toml
I'm marking this as a draft PR since Diataxis documentation should always be complete and this is by definition not, but it's a starting point for writing the documentation.
> docs: Bring basic docs structure from starbase

- .readthedocs.yml
This uses pyproject.toml's docs deps.
> docs: configure readthedocs.yml

- craft_archives/repo/apt_key_manager.py
- craft_archives/repo/package_repository.py
- craft_archives/utils.py
-----
A ruff update that added some more checks and a PR being merged around the same time left us with linting issues.
> lint: fix lint issues with newer ruff

- docs/index.rst
> docs: update main page with the standard template

- pyproject.toml
- tests/unit/repo/test_package_repository.py
-----
Added these while I was adding pinning to package repositories. Not a direct requirement of the work item, but I'm going to change some things that weren't fully tested.
> tests: add package repository tests

- .github/workflows/release-publish.yaml
- craft_archives/repo/projects.py
- pyproject.toml
- tests/unit/repo/test_projects.py
> pydantic: add priority to pydantic models

- pyproject.toml
> create v0.0.3 release

- craft_archives/repo/package_repository.py
- pyproject.toml
- tox.ini
> lint: fix ruff linting in tox

- .github/workflows/docs.yaml
- tox.ini
> ci: add documentation build CI step

- pyproject.toml
> docs: update documentation dependencies

- craft_archives/repo/apt_key_manager.py
- craft_archives/repo/installer.py
- tests/integration/repo/test_installer.py
- tests/unit/repo/test_apt_key_manager.py
> Install forwards key

- .github/workflows/release-publish.yaml
- docs/changelog.rst
- pyproject.toml
The PR adds a couple of necessary release-related Starbase changes, and a changelog entry for `1.1.1`.
> Finalize 1.1.1

- .github/workflows/release-publish.yaml
> ci: make release publisher workflow fetch correct tags

- docs/changelog.rst
> docs: changelog for 1.1.2

- craft_archives/repo/apt_sources_manager.py
- tests/unit/repo/test_apt_sources_manager.py
This commit both fixes the order of the parameters in the call to "dpkg --add-architecture" (the parser is picky) and updates the logic to only make said call if the target architecture (that is, the one coming from the package-repository definition) is "compatible" with the host architecture (that is, the architecture of the system running the code).
This is necessary because incompatible mixes typically break the system. For example, adding "armhf" on an "amd64" system breaks subsequent calls to "apt update" because apt will try to fetch package listings for the "armhf" architecture on the default Ubuntu archives, which don't have them.
Therefore, only the following pairs result in adding the target arch:
- host amd64, target i386;
- host arm64, target armhf.
-----
> sources: only add "compatible" architectures

- docs/changelog.rst
> docs: changelog for 1.1.3

- .github/renovate.json5
> ci: fix renovate schedule

- .github/workflows/tests.yaml
- pyproject.toml
- tox.ini
> chore!: bump minimum Python version to 3.10

- tests/integration/repo/test_installer.py
> test: make cloud archive tests optional by distro

- craft_archives/repo/apt_key_manager.py
- craft_archives/repo/apt_sources_manager.py
- craft_archives/repo/apt_uca.py
- craft_archives/repo/package_repository.py
- docs/reference/repo_properties.rst
- tests/unit/repo/test_apt_sources_manager.py
- tests/unit/repo/test_installer.py
- tests/unit/repo/test_package_repository.py
-----
Implement the FO169 spec to adapt craft-archives to imagecraft.
I also documented the `priority` field to be closer to the documentation on snapcraft.io.
> feat: Add needed fields for imagecraft

- .github/workflows/release-publish.yaml
- docs/changelog.rst
> Cleanups and updates for 1.2.0

- .github/workflows/tests.yaml
- craft_archives/repo/apt_sources_manager.py
- craft_archives/repo/package_repository.py
- pyproject.toml
- tests/integration/repo/test_installer.py
- tests/unit/repo/test_package_repository.py
- tox.ini
-----
Breaking changes:
* Minimum python version is now 3.10
* Requires Pydantic 2
> chore!: merge branch 'feature/2.0' into 'main'

- docs/changelog.rst
> docs: add 2.0.0 changelog

- .github/renovate.json5
- .github/workflows/check-renovate.yaml
https://github.com/canonical/starbase/pull/232
> ci: update renovate config for starbase

- pyproject.toml
> docs(deps): update canonical-sphinx

- .github/workflows/release-publish.yaml
- docs/changelog.rst
> docs: release notes for 2.0.1

- uv.lock
> chore: bump jinja2

- docs/explanation/cryptography.rst
- docs/explanation/index.rst
> docs: add cryptography documentation

- craft_archives/repo/apt_uca.py
> chore: fix pyright error

- .github/.jira_sync_config.yaml
This updates the Jira integration to match our new labels
---
CRAFT-4216
> ci: update Jira integration

- .github/workflows/qa.yaml
- tests/integration/repo/test_installer.py
Requires #143
Fixes #144 
CRAFT-3801
> fix: fix tests on arm64

- tests/unit/repo/test_installer.py
> style: fix lint for ruff 0.12

- pyproject.toml
- uv.lock
---
Supercedes #178 and #177, which both appear broken.
> build(test): update pytest dependencies

- README.md
---
Code cov was able to redirect the to the correct url, but this PR corrects them anyway.
> docs: update code cov url

- .github/workflows/release-publish.yaml
> ci: fix publishing workflow
